// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: end-to-end/bookstore.proto

package bookstore

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ListBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksResponse) Reset() {
	*x = ListBooksResponse{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksResponse) ProtoMessage() {}

func (x *ListBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksResponse.ProtoReflect.Descriptor instead.
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{1}
}

func (x *ListBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type ListShelvesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelves       []*Shelf               `protobuf:"bytes,1,rep,name=shelves,proto3" json:"shelves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShelvesResponse) Reset() {
	*x = ListShelvesResponse{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShelvesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShelvesResponse) ProtoMessage() {}

func (x *ListShelvesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShelvesResponse.ProtoReflect.Descriptor instead.
func (*ListShelvesResponse) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{2}
}

func (x *ListShelvesResponse) GetShelves() []*Shelf {
	if x != nil {
		return x.Shelves
	}
	return nil
}

type Shelf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Theme         string                 `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shelf) Reset() {
	*x = Shelf{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shelf) ProtoMessage() {}

func (x *Shelf) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shelf.ProtoReflect.Descriptor instead.
func (*Shelf) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{3}
}

func (x *Shelf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shelf) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateShelfParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         *Shelf                 `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShelfParameters) Reset() {
	*x = CreateShelfParameters{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShelfParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShelfParameters) ProtoMessage() {}

func (x *CreateShelfParameters) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShelfParameters.ProtoReflect.Descriptor instead.
func (*CreateShelfParameters) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{5}
}

func (x *CreateShelfParameters) GetShelf() *Shelf {
	if x != nil {
		return x.Shelf
	}
	return nil
}

type GetShelfParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         int64                  `protobuf:"varint,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfParameters) Reset() {
	*x = GetShelfParameters{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfParameters) ProtoMessage() {}

func (x *GetShelfParameters) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfParameters.ProtoReflect.Descriptor instead.
func (*GetShelfParameters) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{6}
}

func (x *GetShelfParameters) GetShelf() int64 {
	if x != nil {
		return x.Shelf
	}
	return 0
}

type DeleteShelfParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         int64                  `protobuf:"varint,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShelfParameters) Reset() {
	*x = DeleteShelfParameters{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShelfParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShelfParameters) ProtoMessage() {}

func (x *DeleteShelfParameters) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShelfParameters.ProtoReflect.Descriptor instead.
func (*DeleteShelfParameters) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteShelfParameters) GetShelf() int64 {
	if x != nil {
		return x.Shelf
	}
	return 0
}

type ListBooksParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         int64                  `protobuf:"varint,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksParameters) Reset() {
	*x = ListBooksParameters{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksParameters) ProtoMessage() {}

func (x *ListBooksParameters) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksParameters.ProtoReflect.Descriptor instead.
func (*ListBooksParameters) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{8}
}

func (x *ListBooksParameters) GetShelf() int64 {
	if x != nil {
		return x.Shelf
	}
	return 0
}

type CreateBookParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         int64                  `protobuf:"varint,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	Book          *Book                  `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookParameters) Reset() {
	*x = CreateBookParameters{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookParameters) ProtoMessage() {}

func (x *CreateBookParameters) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookParameters.ProtoReflect.Descriptor instead.
func (*CreateBookParameters) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{9}
}

func (x *CreateBookParameters) GetShelf() int64 {
	if x != nil {
		return x.Shelf
	}
	return 0
}

func (x *CreateBookParameters) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type GetBookParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         int64                  `protobuf:"varint,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	Book          int64                  `protobuf:"varint,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookParameters) Reset() {
	*x = GetBookParameters{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookParameters) ProtoMessage() {}

func (x *GetBookParameters) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookParameters.ProtoReflect.Descriptor instead.
func (*GetBookParameters) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{10}
}

func (x *GetBookParameters) GetShelf() int64 {
	if x != nil {
		return x.Shelf
	}
	return 0
}

func (x *GetBookParameters) GetBook() int64 {
	if x != nil {
		return x.Book
	}
	return 0
}

type DeleteBookParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         int64                  `protobuf:"varint,1,opt,name=shelf,proto3" json:"shelf,omitempty"`
	Book          int64                  `protobuf:"varint,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookParameters) Reset() {
	*x = DeleteBookParameters{}
	mi := &file_end_to_end_bookstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookParameters) ProtoMessage() {}

func (x *DeleteBookParameters) ProtoReflect() protoreflect.Message {
	mi := &file_end_to_end_bookstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookParameters.ProtoReflect.Descriptor instead.
func (*DeleteBookParameters) Descriptor() ([]byte, []int) {
	return file_end_to_end_bookstore_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBookParameters) GetShelf() int64 {
	if x != nil {
		return x.Shelf
	}
	return 0
}

func (x *DeleteBookParameters) GetBook() int64 {
	if x != nil {
		return x.Book
	}
	return 0
}

var File_end_to_end_bookstore_proto protoreflect.FileDescriptor

const file_end_to_end_bookstore_proto_rawDesc = "" +
	"\n" +
	"\x1aend-to-end/bookstore.proto\x12\tbookstore\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/descriptor.proto\"H\n" +
	"\x04Book\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\":\n" +
	"\x11ListBooksResponse\x12%\n" +
	"\x05books\x18\x01 \x03(\v2\x0f.bookstore.BookR\x05books\"A\n" +
	"\x13ListShelvesResponse\x12*\n" +
	"\ashelves\x18\x01 \x03(\v2\x10.bookstore.ShelfR\ashelves\"1\n" +
	"\x05Shelf\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05theme\x18\x02 \x01(\tR\x05theme\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x15CreateShelfParameters\x12&\n" +
	"\x05shelf\x18\x01 \x01(\v2\x10.bookstore.ShelfR\x05shelf\"*\n" +
	"\x12GetShelfParameters\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\x03R\x05shelf\"-\n" +
	"\x15DeleteShelfParameters\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\x03R\x05shelf\"+\n" +
	"\x13ListBooksParameters\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\x03R\x05shelf\"Q\n" +
	"\x14CreateBookParameters\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\x03R\x05shelf\x12#\n" +
	"\x04book\x18\x02 \x01(\v2\x0f.bookstore.BookR\x04book\"=\n" +
	"\x11GetBookParameters\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\x03R\x05shelf\x12\x12\n" +
	"\x04book\x18\x02 \x01(\x03R\x04book\"@\n" +
	"\x14DeleteBookParameters\x12\x14\n" +
	"\x05shelf\x18\x01 \x01(\x03R\x05shelf\x12\x12\n" +
	"\x04book\x18\x02 \x01(\x03R\x04book2\xed\x06\n" +
	"\tBookstore\x12W\n" +
	"\vListShelves\x12\x16.google.protobuf.Empty\x1a\x1e.bookstore.ListShelvesResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/shelves\x12Z\n" +
	"\vCreateShelf\x12 .bookstore.CreateShelfParameters\x1a\x10.bookstore.Shelf\"\x17\x82\xd3\xe4\x93\x02\x11:\x05shelf\"\b/shelves\x12Q\n" +
	"\rDeleteShelves\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x10\x82\xd3\xe4\x93\x02\n" +
	"*\b/shelves\x12U\n" +
	"\bGetShelf\x12\x1d.bookstore.GetShelfParameters\x1a\x10.bookstore.Shelf\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/shelves/{shelf}\x12a\n" +
	"\vDeleteShelf\x12 .bookstore.DeleteShelfParameters\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/shelves/{shelf}\x12i\n" +
	"\tListBooks\x12\x1e.bookstore.ListBooksParameters\x1a\x1c.bookstore.ListBooksResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/shelves/{shelf}/books\x12d\n" +
	"\n" +
	"CreateBook\x12\x1f.bookstore.CreateBookParameters\x1a\x0f.bookstore.Book\"$\x82\xd3\xe4\x93\x02\x1e:\x04book\"\x16/shelves/{shelf}/books\x12_\n" +
	"\aGetBook\x12\x1c.bookstore.GetBookParameters\x1a\x0f.bookstore.Book\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/shelves/{shelf}/books/{book}\x12l\n" +
	"\n" +
	"DeleteBook\x12\x1f.bookstore.DeleteBookParameters\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/shelves/{shelf}/books/{book}B\rZ\v.;bookstoreb\x06proto3"

var (
	file_end_to_end_bookstore_proto_rawDescOnce sync.Once
	file_end_to_end_bookstore_proto_rawDescData []byte
)

func file_end_to_end_bookstore_proto_rawDescGZIP() []byte {
	file_end_to_end_bookstore_proto_rawDescOnce.Do(func() {
		file_end_to_end_bookstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_end_to_end_bookstore_proto_rawDesc), len(file_end_to_end_bookstore_proto_rawDesc)))
	})
	return file_end_to_end_bookstore_proto_rawDescData
}

var file_end_to_end_bookstore_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_end_to_end_bookstore_proto_goTypes = []any{
	(*Book)(nil),                  // 0: bookstore.Book
	(*ListBooksResponse)(nil),     // 1: bookstore.ListBooksResponse
	(*ListShelvesResponse)(nil),   // 2: bookstore.ListShelvesResponse
	(*Shelf)(nil),                 // 3: bookstore.Shelf
	(*Error)(nil),                 // 4: bookstore.Error
	(*CreateShelfParameters)(nil), // 5: bookstore.CreateShelfParameters
	(*GetShelfParameters)(nil),    // 6: bookstore.GetShelfParameters
	(*DeleteShelfParameters)(nil), // 7: bookstore.DeleteShelfParameters
	(*ListBooksParameters)(nil),   // 8: bookstore.ListBooksParameters
	(*CreateBookParameters)(nil),  // 9: bookstore.CreateBookParameters
	(*GetBookParameters)(nil),     // 10: bookstore.GetBookParameters
	(*DeleteBookParameters)(nil),  // 11: bookstore.DeleteBookParameters
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_end_to_end_bookstore_proto_depIdxs = []int32{
	0,  // 0: bookstore.ListBooksResponse.books:type_name -> bookstore.Book
	3,  // 1: bookstore.ListShelvesResponse.shelves:type_name -> bookstore.Shelf
	3,  // 2: bookstore.CreateShelfParameters.shelf:type_name -> bookstore.Shelf
	0,  // 3: bookstore.CreateBookParameters.book:type_name -> bookstore.Book
	12, // 4: bookstore.Bookstore.ListShelves:input_type -> google.protobuf.Empty
	5,  // 5: bookstore.Bookstore.CreateShelf:input_type -> bookstore.CreateShelfParameters
	12, // 6: bookstore.Bookstore.DeleteShelves:input_type -> google.protobuf.Empty
	6,  // 7: bookstore.Bookstore.GetShelf:input_type -> bookstore.GetShelfParameters
	7,  // 8: bookstore.Bookstore.DeleteShelf:input_type -> bookstore.DeleteShelfParameters
	8,  // 9: bookstore.Bookstore.ListBooks:input_type -> bookstore.ListBooksParameters
	9,  // 10: bookstore.Bookstore.CreateBook:input_type -> bookstore.CreateBookParameters
	10, // 11: bookstore.Bookstore.GetBook:input_type -> bookstore.GetBookParameters
	11, // 12: bookstore.Bookstore.DeleteBook:input_type -> bookstore.DeleteBookParameters
	2,  // 13: bookstore.Bookstore.ListShelves:output_type -> bookstore.ListShelvesResponse
	3,  // 14: bookstore.Bookstore.CreateShelf:output_type -> bookstore.Shelf
	12, // 15: bookstore.Bookstore.DeleteShelves:output_type -> google.protobuf.Empty
	3,  // 16: bookstore.Bookstore.GetShelf:output_type -> bookstore.Shelf
	12, // 17: bookstore.Bookstore.DeleteShelf:output_type -> google.protobuf.Empty
	1,  // 18: bookstore.Bookstore.ListBooks:output_type -> bookstore.ListBooksResponse
	0,  // 19: bookstore.Bookstore.CreateBook:output_type -> bookstore.Book
	0,  // 20: bookstore.Bookstore.GetBook:output_type -> bookstore.Book
	12, // 21: bookstore.Bookstore.DeleteBook:output_type -> google.protobuf.Empty
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_end_to_end_bookstore_proto_init() }
func file_end_to_end_bookstore_proto_init() {
	if File_end_to_end_bookstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_end_to_end_bookstore_proto_rawDesc), len(file_end_to_end_bookstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_end_to_end_bookstore_proto_goTypes,
		DependencyIndexes: file_end_to_end_bookstore_proto_depIdxs,
		MessageInfos:      file_end_to_end_bookstore_proto_msgTypes,
	}.Build()
	File_end_to_end_bookstore_proto = out.File
	file_end_to_end_bookstore_proto_goTypes = nil
	file_end_to_end_bookstore_proto_depIdxs = nil
}
