name: Release Go Binaries

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: gnostic-grpc
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2

    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://golang.org/dl/go1.15.3.linux-amd64.tar.gz"
        project_path: "./"
        binary_name: gnostic-grpc

        

