name: Release Go Binaries

on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: gnostic-grpc
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get protobuf-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version

      - name: Build Release
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://go.dev/dl/go1.22.10.linux-amd64.tar.gz"
          pre_command: "apt-get install -y protobuf-compiler && protoc --version && go mod tidy && sh ./COMPILE-PROTOS.sh"
          project_path: "./plugin"
          binary_name: gnostic-grpc

